### ISSUE TITLE
I need to speak Pokemon Online business💰

### ISSUE THREAD

**Issue by UnhingedSociety** [coyotte508/mongo-query#1]
I'm not the most familiar with github & i need to talk, but I couldn't find another way to communicate. can you contact me @ UnhingedxSociety@gmail.com?

**Comment by coyotte508** [comment]
you can speak here, I doubt anyone is watching :)

**Comment by UnhingedSociety** [comment]
can you give me a monetary estimate of how much it would cost monthly to revive Pokemon Online's Online accessibility? and if anyone is available to implement small updates?

**Comment by SteveC688** [comment]
Hi UnhingedSociety,

I have dropped you an e-mail regarding this.

Many thanks,
Stephen
